// Gorgon mock data — shared weekend-activity dataset for the app UI kit.
//
// ⚠️ 样例数据说明:以下活动锚定在「真实存在的上海场馆 / 高校周边地点」,坐标为近似值,
//    用作填真实数据的样板。具体场次、时间、票价务必通过 source 核实后再替换,
//    凡未经主办方确认的一律标 trust:"aggregated" 或 "unverified"。
window.GORGON_DATA = {
  user: { name: "小林", campus: "上海·杨浦", coord: { lng: 121.51, lat: 31.30 }, avatar: "" },
  categories: [
    { key: "all", label: "全部" },
    { key: "sport", label: "运动" },
    { key: "music", label: "音乐" },
    { key: "art", label: "艺术" },
    { key: "food", label: "美食" },
    { key: "outdoor", label: "户外" },
    { key: "study", label: "学习" },
  ],
  activities: [
    {
      id: "r1", title: "大学路周末市集 · 手作与咖啡", category: "food",
      date: "周六 6.20", day: "sat", time: "11:00", end: "18:00",
      location: "上海·杨浦", venue: "大学路", distance: "0.9km",
      address: "上海市杨浦区大学路(复旦、财大、上理工环绕的步行街)",
      coord: { lng: 121.5085, lat: 31.3045 },
      price: "免费", hot: true, going: 240, capacity: null, spotsLeft: null,
      tags: ["市集", "咖啡", "手作"],
      trust: "aggregated", source: "小红书 / 大学路商户", updated: "昨天",
      host: "大学路商街", contact: "现场无需报名,样例信息请以商街公告为准",
      desc: "大学路周末的露天市集:独立咖啡、手作摊位、二手好物。复旦、财大学生步行可达,适合午后闲逛。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "国权路站 1 号口步行 8 分钟", time: "16 分钟", cost: "¥3", recommended: true },
        { mode: "bike", line: "共享单车", detail: "校区出发沿政立路骑行", time: "6 分钟", cost: "¥1.5" },
        { mode: "walk", line: "步行", detail: "全程 0.9km", time: "12 分钟" },
      ],
      bring: ["环保袋", "学生证(部分摊位有学生价)"],
      notes: "聚合自社交平台,具体摊位与时间以现场为准。雨天部分摊位撤场。",
      refund: "免费活动,无需退款。",
    },
    {
      id: "r2", title: "西岸美术馆大道 · 周末特展", category: "art",
      date: "周六 6.20", day: "sat", time: "10:00", end: "17:00",
      location: "上海·徐汇", venue: "西岸美术馆", distance: "6.8km",
      address: "上海市徐汇区龙腾大道 2600 号 · 西岸美术馆(徐汇滨江)",
      coord: { lng: 121.4625, lat: 31.1762 },
      price: "学生 ¥60", hot: true, going: 320, capacity: 500, spotsLeft: 180,
      tags: ["特展", "滨江", "学生票"],
      trust: "official", source: "西岸美术馆官网", updated: "今天",
      host: "西岸美术馆", contact: "官网 / 官方小程序购票",
      desc: "徐汇滨江的西岸美术馆周末特展,凭学生证可购学生票。看完展可沿江散步到龙美术馆。",
      transit: [
        { mode: "metro", line: "地铁 11 号线", detail: "云锦路站 2 号口步行 9 分钟", time: "34 分钟", cost: "¥5", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 7 公里", time: "22 分钟", cost: "¥28" },
        { mode: "bus", line: "公交 龙华-滨江线", detail: "美术馆大道站下", time: "41 分钟", cost: "¥2" },
      ],
      bring: ["学生证", "已购票二维码"],
      notes: "正式场馆信息,展期与票价以官网为准。周末客流大,建议线上预约时段。",
      refund: "开展前 24 小时可在原渠道退票,逾期不退。",
    },
    {
      id: "r3", title: "M50 创意园 · 艺术家开放工作室", category: "art",
      date: "周六 6.20", day: "sat", time: "13:00", end: "18:00",
      location: "上海·普陀", venue: "M50 创意园", distance: "4.2km",
      address: "上海市普陀区莫干山路 50 号 · M50 创意园(苏州河畔)",
      coord: { lng: 121.4432, lat: 31.2520 },
      price: "免费", hot: false, going: 86, capacity: 150, spotsLeft: 64,
      tags: ["开放工作室", "画廊", "免费"],
      trust: "verified", source: "M50 官方公众号", updated: "3 小时前",
      host: "M50 创意园", contact: "公众号「M50创意园」",
      desc: "苏州河畔的 M50,周末部分艺术家工作室开放参观,可与创作者交流。华师大、同济沪西校区步行+地铁可达。",
      transit: [
        { mode: "metro", line: "地铁 13 号线", detail: "江宁路站 4 号口步行 11 分钟", time: "26 分钟", cost: "¥4", recommended: true },
        { mode: "bike", line: "共享单车", detail: "沿苏州河骑行", time: "15 分钟", cost: "¥1.5" },
        { mode: "taxi", line: "打车", detail: "约 4 公里", time: "15 分钟", cost: "¥19" },
      ],
      bring: ["相机(部分工作室可拍照)"],
      notes: "开放工作室名单每周不同,以当周公众号推送为准。",
      refund: "免费参观,无需退款。",
    },
    {
      id: "r4", title: "共青森林公园 · 晨间观鸟团", category: "outdoor",
      date: "周日 6.21", day: "sun", time: "07:00", end: "09:30",
      location: "上海·杨浦", venue: "共青森林公园南门", distance: "3.5km",
      address: "上海市杨浦区军工路 2000 号 · 共青森林公园南门集合",
      coord: { lng: 121.5460, lat: 31.3180 },
      price: "门票 ¥15", hot: false, going: 18, capacity: 30, spotsLeft: 12,
      tags: ["观鸟", "新手友好", "早起"],
      trust: "aggregated", source: "豆瓣同城 · 上海观鸟", updated: "昨天",
      host: "周末自然观察小组", contact: "豆瓣小组「上海观鸟」",
      desc: "清晨在共青森林公园认鸟,有领队讲解、可借望远镜。复旦、同济学生公交可达,适合想早起亲近自然的人。",
      transit: [
        { mode: "bus", line: "公交 8 路", detail: "共青森林公园站下车即到", time: "22 分钟", cost: "¥2", recommended: true },
        { mode: "bike", line: "共享单车", detail: "沿军工路骑行", time: "16 分钟", cost: "¥1.5" },
        { mode: "taxi", line: "打车", detail: "约 3.5 公里", time: "12 分钟", cost: "¥16" },
      ],
      bring: ["望远镜(可借)", "饮用水", "防蚊"],
      notes: "豆瓣聚合信息,时间地点以当日小组公告为准。雨天取消。公园另需 ¥15 门票。",
      refund: "活动免费,公园门票自理;不能到场请提前在小组取消。",
    },
    {
      id: "r5", title: "顾村公园 · 周末骑行野餐", category: "outdoor",
      date: "周日 6.21", day: "sun", time: "15:00", end: "18:00",
      location: "上海·宝山", venue: "顾村公园 1 号门", distance: "1.1km",
      address: "上海市宝山区沪太路 4788 号 · 顾村公园 1 号门(上海大学旁)",
      coord: { lng: 121.4015, lat: 31.3905 },
      price: "门票 ¥20", hot: false, going: 42, capacity: 80, spotsLeft: 38,
      tags: ["骑行", "野餐", "看日落"],
      trust: "aggregated", source: "微信群 · 上大周末", updated: "2 天前",
      host: "上大周末骑行", contact: "投稿群信息,未经场地方确认",
      desc: "顾村公园内骑行一圈再草坪野餐,看一次日落。上海大学学生步行可达,适合三五结伴。",
      transit: [
        { mode: "metro", line: "地铁 7 号线", detail: "顾村公园站 1 号口即到", time: "8 分钟", cost: "¥3", recommended: true },
        { mode: "walk", line: "步行", detail: "上大校区出发 1.1km", time: "15 分钟" },
        { mode: "bike", line: "共享单车", detail: "沿沪太路骑行", time: "6 分钟", cost: "¥1.5" },
      ],
      bring: ["野餐垫", "食物饮水", "公园门票 ¥20"],
      notes: "群聊聚合,具体集合点请进群确认。园内骑行需租车或自带。",
      refund: "活动免费,门票自理。",
    },
    {
      id: "r6", title: "钱学森图书馆 · 周末公益讲座", category: "study",
      date: "周日 6.21", day: "sun", time: "14:00", end: "15:30",
      location: "上海·徐汇", venue: "上海交大钱学森图书馆", distance: "5.6km",
      address: "上海市徐汇区华山路 1800 号 · 上海交通大学钱学森图书馆",
      coord: { lng: 121.4335, lat: 31.2010 },
      price: "免费", hot: false, going: 60, capacity: 120, spotsLeft: 60,
      tags: ["讲座", "免费", "需预约"],
      trust: "official", source: "钱学森图书馆官网", updated: "今天",
      host: "钱学森图书馆", contact: "官网 / 官方公众号预约",
      desc: "上海交大钱学森图书馆周末公益科普讲座,免费但需提前线上预约,凭预约码入场。各校学生均可参加。",
      transit: [
        { mode: "metro", line: "地铁 10/11 号线", detail: "交通大学站 1 号口步行 6 分钟", time: "30 分钟", cost: "¥5", recommended: true },
        { mode: "bus", line: "公交 911 路", detail: "华山路淮海西路站", time: "38 分钟", cost: "¥2" },
        { mode: "taxi", line: "打车", detail: "约 6 公里", time: "20 分钟", cost: "¥24" },
      ],
      bring: ["预约码", "学生证"],
      notes: "正式场馆信息,场次与名额以官网预约为准。迟到 15 分钟视为放弃。",
      refund: "免费讲座,如不能到场请提前在官网取消预约,方便他人。",
    },
  ],
};
