// Gorgon Demo MVP — weekend-activity dataset.
//
// ⚠️⚠️  DEMO DATA — 全部为演示用样例，不是真实活动  ⚠️⚠️
// -----------------------------------------------------------------------------
// 本文件中每一条活动都带有 `demo: true` 标记，`source` 一律以 "DEMO DATA" 开头。
// 时间、票价、主办方、报名链接均为示例，请勿据此前往或付款。
// 字段结构沿用恢复版本的 schema；仅新增 district / image / registrationUrl 三个字段。
//
// demo items: 24 条，覆盖 科技 / 黑客松 / 展览 / 音乐 / 运动 / 市集 / 讲座 / 社交 / 校园 / 公益。
// -----------------------------------------------------------------------------
window.GORGON_DATA = {
  DEMO: true,
  notice: "DEMO DATA — 演示样例数据，非真实活动",
  user: { name: "小林", campus: "上海·杨浦", coord: { lng: 121.51, lat: 31.30 }, avatar: "" },
  categories: [
    { key: "all", label: "全部" },
    { key: "ai", label: "科技" },
    { key: "hackathon", label: "黑客松" },
    { key: "exhibition", label: "展览" },
    { key: "music", label: "音乐" },
    { key: "sport", label: "运动" },
    { key: "market", label: "市集" },
    { key: "talk", label: "讲座" },
    { key: "social", label: "社交" },
    { key: "campus", label: "校园" },
    { key: "charity", label: "公益" },
    { key: "art", label: "艺术" },
    { key: "food", label: "美食" },
    { key: "outdoor", label: "户外" },
    { key: "study", label: "学习" },
  ],
  activities: [
    {
      id: "d01", demo: true, image: null, title: "AI 产品开放日 · 生成式应用 Demo Night", category: "ai",
      date: "周六 6.20", day: "sat", time: "19:00", end: "21:30",
      location: "上海·徐汇", district: "徐汇", venue: "西岸智塔 AI 空间", distance: "6.4km",
      address: "上海市徐汇区龙腾大道 · 西岸智塔（示例地址）",
      coord: { lng: 121.4630, lat: 31.1790 },
      price: "免费", hot: true, going: 180, capacity: 220, spotsLeft: 40,
      tags: ["AI", "生成式", "Demo", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（AI 社区）", updated: "今天",
      host: "上海 AI 开发者社区（示例）", contact: "示例报名入口，非真实链接",
      desc: "十多个学生与独立开发者带着自己的生成式应用上台路演，涵盖写作、图像、Agent 等方向，适合想了解 AI 产品落地形态的同学围观交流。",
      transit: [
        { mode: "metro", line: "地铁 11 号线", detail: "云锦路站步行 9 分钟", time: "34 分钟", cost: "¥5", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 6.5 公里", time: "22 分钟", cost: "¥26" },
      ],
      bring: ["学生证"], notes: "DEMO 数据，时间地点均为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d01",
    },
    {
      id: "d02", demo: true, image: null, title: "大模型应用实战工作坊（零基础）", category: "ai",
      date: "周日 6.21", day: "sun", time: "13:30", end: "17:00",
      location: "上海·杨浦", district: "杨浦", venue: "创智天地 7 号楼", distance: "1.6km",
      address: "上海市杨浦区淞沪路 · 创智天地（示例地址）",
      coord: { lng: 121.5175, lat: 31.3060 },
      price: "学生 ¥29", hot: false, going: 48, capacity: 60, spotsLeft: 12,
      tags: ["AI", "工作坊", "零基础", "手把手"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（校内社团）", updated: "昨天",
      host: "复旦 AI 研习社（示例）", contact: "示例报名入口，非真实链接",
      desc: "从零开始用提示词搭一个能跑的小应用，讲师全程带着做。不需要编程基础，带笔记本电脑即可。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "江湾体育场站步行 5 分钟", time: "11 分钟", cost: "¥3", recommended: true },
        { mode: "bike", line: "共享单车", detail: "校区出发约 1.6km", time: "8 分钟", cost: "¥1.5" },
      ],
      bring: ["笔记本电脑", "学生证"], notes: "DEMO 数据，场次与名额均为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d02",
    },
    {
      id: "d03", demo: true, image: null, title: "48h 城市 Hackathon · 智慧校园赛道", category: "hackathon",
      date: "周六 6.20", day: "sat", time: "09:00", end: "21:00",
      location: "上海·杨浦", district: "杨浦", venue: "同济设计创意学院", distance: "2.1km",
      address: "上海市杨浦区阜新路 · 同济设计创意学院（示例地址）",
      coord: { lng: 121.5060, lat: 31.2830 },
      price: "免费", hot: true, going: 132, capacity: 150, spotsLeft: 18,
      tags: ["hackathon", "黑客松", "组队", "48小时"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（赛事官网）", updated: "今天",
      host: "同济创客中心（示例）", contact: "示例报名入口，非真实链接",
      desc: "48 小时现场组队，围绕「智慧校园」做产品原型。提供场地、餐食和导师，最后一天路演评奖，适合想找队友的学生。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "同济大学站步行 6 分钟", time: "14 分钟", cost: "¥3", recommended: true },
        { mode: "walk", line: "步行", detail: "全程 2.1km", time: "28 分钟" },
      ],
      bring: ["电脑", "充电器", "睡袋（可选）"], notes: "DEMO 数据，赛事信息为示例。", refund: "免费活动，报名后请按时到场。",
      registrationUrl: "https://example.com/gorgon-demo/d03",
    },
    {
      id: "d04", demo: true, image: null, title: "AI Agent 黑客松 · 周末闪电赛", category: "hackathon",
      date: "周日 6.21", day: "sun", time: "10:00", end: "20:00",
      location: "上海·浦东", district: "浦东", venue: "张江科学会堂", distance: "12.3km",
      address: "上海市浦东新区海科路 · 张江科学会堂（示例地址）",
      coord: { lng: 121.6040, lat: 31.2050 },
      price: "¥50（含餐）", hot: false, going: 96, capacity: 120, spotsLeft: 24,
      tags: ["hackathon", "Agent", "一天", "含餐"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（企业开放平台）", updated: "3 小时前",
      host: "张江开发者关系团队（示例）", contact: "示例报名入口，非真实链接",
      desc: "一天之内把 Agent 从想法做到能演示，主题自由。现场有 API 额度与工程师答疑，适合已有一定基础的同学冲刺。",
      transit: [
        { mode: "metro", line: "地铁 13 号线", detail: "华夏中路站换乘接驳", time: "58 分钟", cost: "¥7", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 12 公里", time: "35 分钟", cost: "¥48" },
      ],
      bring: ["电脑", "学生证"], notes: "DEMO 数据，含餐信息为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d04",
    },
    {
      id: "d05", demo: true, image: null, title: "西岸美术馆 · 当代影像特展「此刻」", category: "exhibition",
      date: "周六 6.20", day: "sat", time: "10:00", end: "17:00",
      location: "上海·徐汇", district: "徐汇", venue: "西岸美术馆", distance: "6.8km",
      address: "上海市徐汇区龙腾大道 2600 号 · 西岸美术馆（示例地址）",
      coord: { lng: 121.4625, lat: 31.1762 },
      price: "学生 ¥60", hot: true, going: 320, capacity: 500, spotsLeft: 180,
      tags: ["展览", "影像", "滨江", "学生票"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（美术馆官网）", updated: "今天",
      host: "西岸美术馆（示例）", contact: "示例报名入口，非真实链接",
      desc: "聚焦当代影像创作的特展，凭学生证可购学生票。看完展可沿徐汇滨江散步到龙美术馆，适合安排半天的文艺行程。",
      transit: [
        { mode: "metro", line: "地铁 11 号线", detail: "云锦路站 2 号口步行 9 分钟", time: "34 分钟", cost: "¥5", recommended: true },
        { mode: "bus", line: "公交 滨江线", detail: "美术馆大道站下", time: "41 分钟", cost: "¥2" },
      ],
      bring: ["学生证", "预约二维码"], notes: "DEMO 数据，展期与票价为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d05",
    },
    {
      id: "d06", demo: true, image: null, title: "M50 创意园 · 青年艺术家联展「边界」", category: "exhibition",
      date: "周六 6.20", day: "sat", time: "13:00", end: "18:00",
      location: "上海·普陀", district: "普陀", venue: "M50 创意园", distance: "4.2km",
      address: "上海市普陀区莫干山路 50 号 · M50 创意园（示例地址）",
      coord: { lng: 121.4432, lat: 31.2520 },
      price: "免费", hot: false, going: 86, capacity: 150, spotsLeft: 64,
      tags: ["展览", "青年艺术家", "免费", "苏州河"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（园区公众号）", updated: "昨天",
      host: "M50 创意园（示例）", contact: "示例报名入口，非真实链接",
      desc: "苏州河畔的 M50 联展，十几位青年艺术家围绕「边界」主题创作，周末部分工作室开放参观，可与创作者当面交流。",
      transit: [
        { mode: "metro", line: "地铁 13 号线", detail: "江宁路站步行 11 分钟", time: "26 分钟", cost: "¥4", recommended: true },
        { mode: "bike", line: "共享单车", detail: "沿苏州河骑行", time: "15 分钟", cost: "¥1.5" },
      ],
      bring: ["相机（部分工作室可拍照）"], notes: "DEMO 数据，名单与时间均为示例。", refund: "免费参观，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d06",
    },
    {
      id: "d07", demo: true, image: null, title: "Livehouse 周末原创之夜", category: "music",
      date: "周六 6.20", day: "sat", time: "20:00", end: "23:00",
      location: "上海·静安", district: "静安", venue: "育音堂（示例场地）", distance: "5.1km",
      address: "上海市静安区昌化路 · 育音堂（示例地址）",
      coord: { lng: 121.4520, lat: 31.2430 },
      price: "预售 ¥80", hot: true, going: 210, capacity: 300, spotsLeft: 90,
      tags: ["音乐", "Livehouse", "原创", "乐队"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（场地方）", updated: "今天",
      host: "育音堂（示例）", contact: "示例报名入口，非真实链接",
      desc: "三支本地原创乐队轮番上阵，票价含一杯饮品。适合喜欢现场感、想认识同好乐迷的同学。",
      transit: [
        { mode: "metro", line: "地铁 1/12/13 号线", detail: "汉中路站步行 8 分钟", time: "31 分钟", cost: "¥5", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 5 公里", time: "20 分钟", cost: "¥22" },
      ],
      bring: ["身份证（部分场次核验）"], notes: "DEMO 数据，乐队与票价为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d07",
    },
    {
      id: "d08", demo: true, image: null, title: "校园草坪音乐节 · 学生乐队专场", category: "music",
      date: "周日 6.21", day: "sun", time: "16:00", end: "21:00",
      location: "上海·杨浦", district: "杨浦", venue: "复旦江湾校区草坪", distance: "2.8km",
      address: "上海市杨浦区淞沪路 2005 号 · 江湾校区草坪（示例地址）",
      coord: { lng: 121.5230, lat: 31.3250 },
      price: "免费", hot: true, going: 430, capacity: 800, spotsLeft: 370,
      tags: ["音乐", "音乐节", "校园", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（学生会）", updated: "今天",
      host: "复旦学生会（示例）", contact: "示例报名入口，非真实链接",
      desc: "草坪上的学生乐队专场，从黄昏唱到夜里。自带野餐垫就能待一下午，是全校园最热闹的周末活动之一。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "新江湾城站步行 12 分钟", time: "19 分钟", cost: "¥3", recommended: true },
        { mode: "bike", line: "共享单车", detail: "校区出发约 2.8km", time: "11 分钟", cost: "¥1.5" },
      ],
      bring: ["野餐垫", "水", "学生证"], notes: "DEMO 数据，阵容为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d08",
    },
    {
      id: "d09", demo: true, image: null, title: "苏州河晨跑团 · 10km 配速组", category: "sport",
      date: "周六 6.20", day: "sat", time: "07:00", end: "08:30",
      location: "上海·普陀", district: "普陀", venue: "苏州河梦清园", distance: "3.9km",
      address: "上海市普陀区宜昌路 · 梦清园集合（示例地址）",
      coord: { lng: 121.4400, lat: 31.2460 },
      price: "免费", hot: false, going: 36, capacity: 50, spotsLeft: 14,
      tags: ["运动", "跑步", "晨跑", "配速"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（跑团群）", updated: "昨天",
      host: "苏州河晨跑团（示例）", contact: "示例报名入口，非真实链接",
      desc: "沿苏州河跑一个 10 公里，分 5'30\" / 6'00\" 两个配速组，有领跑员。跑完一起吃早点，新手也能跟上。",
      transit: [
        { mode: "bike", line: "共享单车", detail: "沿河骑行到集合点", time: "14 分钟", cost: "¥1.5", recommended: true },
        { mode: "metro", line: "地铁 3/4 号线", detail: "中潭路站步行 10 分钟", time: "24 分钟", cost: "¥4" },
      ],
      bring: ["跑鞋", "水", "毛巾"], notes: "DEMO 数据，集合点与时间为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d09",
    },
    {
      id: "d10", demo: true, image: null, title: "高校羽毛球交友局 · 周末双打", category: "sport",
      date: "周日 6.21", day: "sun", time: "14:00", end: "16:00",
      location: "上海·徐汇", district: "徐汇", venue: "交大徐汇体育馆", distance: "5.6km",
      address: "上海市徐汇区华山路 1954 号 · 交大体育馆（示例地址）",
      coord: { lng: 121.4340, lat: 31.2000 },
      price: "¥25（场地AA）", hot: false, going: 28, capacity: 32, spotsLeft: 4,
      tags: ["运动", "羽毛球", "交友", "双打"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（校内运动群）", updated: "2 天前",
      host: "交大羽毛球社（示例）", contact: "示例报名入口，非真实链接",
      desc: "随机组队双打，水平不限，主打一个边打边认识新朋友。费用 AA 场地费，自带球拍。",
      transit: [
        { mode: "metro", line: "地铁 10/11 号线", detail: "交通大学站步行 6 分钟", time: "30 分钟", cost: "¥5", recommended: true },
        { mode: "bus", line: "公交 911 路", detail: "华山路站下", time: "38 分钟", cost: "¥2" },
      ],
      bring: ["球拍", "运动鞋", "学生证"], notes: "DEMO 数据，场地与费用为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d10",
    },
    {
      id: "d11", demo: true, image: null, title: "大学路周末市集 · 手作与咖啡", category: "market",
      date: "周六 6.20", day: "sat", time: "11:00", end: "18:00",
      location: "上海·杨浦", district: "杨浦", venue: "大学路", distance: "0.9km",
      address: "上海市杨浦区大学路步行街（示例地址）",
      coord: { lng: 121.5085, lat: 31.3045 },
      price: "免费", hot: true, going: 240, capacity: null, spotsLeft: null,
      tags: ["市集", "咖啡", "手作", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（商街）", updated: "昨天",
      host: "大学路商街（示例）", contact: "现场无需报名（示例）",
      desc: "露天市集：独立咖啡、手作摊位、二手好物。步行可达，适合午后闲逛，雨天部分摊位撤场。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "国权路站 1 号口步行 8 分钟", time: "16 分钟", cost: "¥3", recommended: true },
        { mode: "walk", line: "步行", detail: "全程 0.9km", time: "12 分钟" },
      ],
      bring: ["环保袋", "学生证（部分摊位有学生价）"], notes: "DEMO 数据，摊位为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d11",
    },
    {
      id: "d12", demo: true, image: null, title: "旧书与黑胶市集 · 循环生活日", category: "market",
      date: "周日 6.21", day: "sun", time: "12:00", end: "19:00",
      location: "上海·黄浦", district: "黄浦", venue: "思南公馆露天区", distance: "7.2km",
      address: "上海市黄浦区复兴中路 517 号 · 思南公馆（示例地址）",
      coord: { lng: 121.4700, lat: 31.2130 },
      price: "免费", hot: false, going: 156, capacity: null, spotsLeft: null,
      tags: ["市集", "旧书", "黑胶", "循环"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（市集主办）", updated: "3 小时前",
      host: "循环生活市集（示例）", contact: "现场无需报名（示例）",
      desc: "旧书、黑胶、复古杂货的循环市集，可以带自己的闲置来交换。适合喜欢淘书的文青同学。",
      transit: [
        { mode: "metro", line: "地铁 13 号线", detail: "淮海中路站步行 7 分钟", time: "36 分钟", cost: "¥5", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 7 公里", time: "26 分钟", cost: "¥30" },
      ],
      bring: ["可交换的闲置"], notes: "DEMO 数据，摊位为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d12",
    },
    {
      id: "d13", demo: true, image: null, title: "钱学森图书馆 · 周末公益科普讲座", category: "talk",
      date: "周日 6.21", day: "sun", time: "14:00", end: "15:30",
      location: "上海·徐汇", district: "徐汇", venue: "钱学森图书馆", distance: "5.6km",
      address: "上海市徐汇区华山路 1800 号 · 钱学森图书馆（示例地址）",
      coord: { lng: 121.4335, lat: 31.2010 },
      price: "免费", hot: false, going: 60, capacity: 120, spotsLeft: 60,
      tags: ["讲座", "公益", "科普", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（场馆官网）", updated: "今天",
      host: "钱学森图书馆（示例）", contact: "示例报名入口，非真实链接",
      desc: "面向公众的科普讲座，免费但需预约，凭预约码入场。各校学生均可参加，迟到 15 分钟视为放弃。",
      transit: [
        { mode: "metro", line: "地铁 10/11 号线", detail: "交通大学站步行 6 分钟", time: "30 分钟", cost: "¥5", recommended: true },
        { mode: "bus", line: "公交 911 路", detail: "华山路淮海西路站", time: "38 分钟", cost: "¥2" },
      ],
      bring: ["预约码", "学生证"], notes: "DEMO 数据，场次为示例。", refund: "免费讲座，如不能到场请提前取消（示例）。",
      registrationUrl: "https://example.com/gorgon-demo/d13",
    },
    {
      id: "d14", demo: true, image: null, title: "AI 与就业 · 行业前辈分享会", category: "talk",
      date: "周六 6.20", day: "sat", time: "15:00", end: "17:00",
      location: "上海·杨浦", district: "杨浦", venue: "创智天地 会议中心", distance: "1.7km",
      address: "上海市杨浦区淞沪路 · 创智天地会议中心（示例地址）",
      coord: { lng: 121.5170, lat: 31.3065 },
      price: "免费", hot: true, going: 142, capacity: 180, spotsLeft: 38,
      tags: ["讲座", "AI", "就业", "分享会"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（职业发展中心）", updated: "今天",
      host: "高校职业发展中心（示例）", contact: "示例报名入口，非真实链接",
      desc: "三位在 AI 行业工作的学长学姐聊真实的一线经验：岗位在招什么、简历怎么写、要不要读研。后半场自由提问。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "江湾体育场站步行 5 分钟", time: "11 分钟", cost: "¥3", recommended: true },
        { mode: "bike", line: "共享单车", detail: "约 1.7km", time: "8 分钟", cost: "¥1.5" },
      ],
      bring: ["学生证", "简历（可选）"], notes: "DEMO 数据，嘉宾为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d14",
    },
    {
      id: "d15", demo: true, image: null, title: "陌生人晚餐 · 8 人桌", category: "social",
      date: "周六 6.20", day: "sat", time: "18:30", end: "21:00",
      location: "上海·静安", district: "静安", venue: "静安寺附近餐厅", distance: "4.8km",
      address: "上海市静安区愚园路（示例地址）",
      coord: { lng: 121.4450, lat: 31.2240 },
      price: "¥88（餐费AA）", hot: false, going: 8, capacity: 8, spotsLeft: 0,
      tags: ["社交", "晚餐", "陌生人", "小而美"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（活动群）", updated: "昨天",
      host: "城市社交实验室（示例）", contact: "示例报名入口，非真实链接",
      desc: "一桌 8 个陌生人吃饭，主办方准备了几个话题卡帮忙破冰。适合想扩大社交圈但不喜欢大型活动的同学。",
      transit: [
        { mode: "metro", line: "地铁 2/7 号线", detail: "静安寺站步行 6 分钟", time: "28 分钟", cost: "¥5", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 5 公里", time: "19 分钟", cost: "¥21" },
      ],
      bring: ["好心情"], notes: "DEMO 数据，餐厅与费用为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d15",
    },
    {
      id: "d16", demo: true, image: null, title: "桌游之夜 · 德式策略专场", category: "social",
      date: "周日 6.21", day: "sun", time: "19:00", end: "22:30",
      location: "上海·长宁", district: "长宁", venue: "中山公园旁桌游吧", distance: "5.4km",
      address: "上海市长宁区长宁路（示例地址）",
      coord: { lng: 121.4180, lat: 31.2200 },
      price: "¥40（含饮料）", hot: false, going: 18, capacity: 24, spotsLeft: 6,
      tags: ["社交", "桌游", "策略", "新手友好"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（桌游社）", updated: "2 天前",
      host: "长宁桌游社（示例）", contact: "示例报名入口，非真实链接",
      desc: "主打德式策略桌游，有桌长带新手。四个人一桌，玩到尽兴为止，含一杯饮料。",
      transit: [
        { mode: "metro", line: "地铁 2/3/4 号线", detail: "中山公园站步行 5 分钟", time: "27 分钟", cost: "¥5", recommended: true },
        { mode: "bike", line: "共享单车", detail: "约 5km", time: "20 分钟", cost: "¥1.5" },
      ],
      bring: ["学生证"], notes: "DEMO 数据，场地为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d16",
    },
    {
      id: "d17", demo: true, image: null, title: "交大夏日开放日 · 实验室参观", category: "campus",
      date: "周六 6.20", day: "sat", time: "09:30", end: "12:00",
      location: "上海·闵行", district: "闵行", venue: "上海交大闵行校区", distance: "18.5km",
      address: "上海市闵行区东川路 800 号 · 交大闵行校区（示例地址）",
      coord: { lng: 121.4340, lat: 31.0250 },
      price: "免费", hot: false, going: 88, capacity: 100, spotsLeft: 12,
      tags: ["校园", "开放日", "实验室", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（校方）", updated: "昨天",
      host: "上海交大（示例）", contact: "示例报名入口，非真实链接",
      desc: "开放日参观几个重点实验室，有在读博士生讲解。对理工科方向感兴趣、想了解科研生活的高中生和低年级同学尤其适合。",
      transit: [
        { mode: "metro", line: "地铁 5 号线", detail: "东川路站换乘接驳", time: "72 分钟", cost: "¥7", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 18 公里", time: "45 分钟", cost: "¥62" },
      ],
      bring: ["学生证", "身份证"], notes: "DEMO 数据，行程为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d17",
    },
    {
      id: "d18", demo: true, image: null, title: "社团招新嘉年华 · 百团大战", category: "campus",
      date: "周日 6.21", day: "sun", time: "10:00", end: "16:00",
      location: "上海·杨浦", district: "杨浦", venue: "复旦邯郸校区中央大道", distance: "1.2km",
      address: "上海市杨浦区邯郸路 220 号（示例地址）",
      coord: { lng: 121.5060, lat: 31.2980 },
      price: "免费", hot: true, going: 520, capacity: null, spotsLeft: null,
      tags: ["校园", "社团", "招新", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（社团联合会）", updated: "今天",
      host: "社团联合会（示例）", contact: "现场参与（示例）",
      desc: "上百个社团摆摊招新，从街舞到天文什么都有。逛一圈基本能确定这学期的兴趣方向，还能领到不少小周边。",
      transit: [
        { mode: "metro", line: "地铁 10 号线", detail: "国权路站步行 10 分钟", time: "17 分钟", cost: "¥3", recommended: true },
        { mode: "walk", line: "步行", detail: "全程 1.2km", time: "16 分钟" },
      ],
      bring: ["学生证"], notes: "DEMO 数据，社团为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d18",
    },
    {
      id: "d19", demo: true, image: null, title: "流浪动物领养日 · 义工招募", category: "charity",
      date: "周六 6.20", day: "sat", time: "13:00", end: "17:00",
      location: "上海·宝山", district: "宝山", venue: "顾村公园北门广场", distance: "1.4km",
      address: "上海市宝山区沪太路 4788 号 · 顾村公园北门（示例地址）",
      coord: { lng: 121.4010, lat: 31.3910 },
      price: "免费", hot: false, going: 64, capacity: 80, spotsLeft: 16,
      tags: ["公益", "领养", "义工", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（动物救助组织）", updated: "昨天",
      host: "城市流浪动物救助（示例）", contact: "示例报名入口，非真实链接",
      desc: "现场有等待领养的猫狗，也可以报名做当天义工（布置场地、遛狗、拍照）。领养需签署协议并接受回访。",
      transit: [
        { mode: "metro", line: "地铁 7 号线", detail: "顾村公园站 1 号口", time: "9 分钟", cost: "¥3", recommended: true },
        { mode: "walk", line: "步行", detail: "校区出发 1.4km", time: "19 分钟" },
      ],
      bring: ["旧毛巾（捐赠）", "学生证"], notes: "DEMO 数据，组织与流程为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d19",
    },
    {
      id: "d20", demo: true, image: null, title: "旧衣回收 · 环保换礼日", category: "charity",
      date: "周日 6.21", day: "sun", time: "11:00", end: "16:00",
      location: "上海·虹口", district: "虹口", venue: "鲁迅公园门口", distance: "4.6km",
      address: "上海市虹口区四川北路 2288 号 · 鲁迅公园（示例地址）",
      coord: { lng: 121.4790, lat: 31.2700 },
      price: "免费", hot: false, going: 74, capacity: 100, spotsLeft: 26,
      tags: ["公益", "环保", "回收", "免费"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（环保公益组织）", updated: "2 天前",
      host: "循环公益联盟（示例）", contact: "现场参与（示例）",
      desc: "带旧衣物来回收，按重量兑换小礼品（帆布袋 / 咖啡券）。现场还有旧物改造的小课堂。",
      transit: [
        { mode: "metro", line: "地铁 3/8 号线", detail: "虹口足球场站步行 9 分钟", time: "29 分钟", cost: "¥4", recommended: true },
        { mode: "bike", line: "共享单车", detail: "约 4.6km", time: "18 分钟", cost: "¥1.5" },
      ],
      bring: ["旧衣物"], notes: "DEMO 数据，兑换规则为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d20",
    },
    {
      id: "d21", demo: true, image: null, title: "陶艺体验 · 手作一个自己的杯子", category: "art",
      date: "周六 6.20", day: "sat", time: "14:00", end: "16:30",
      location: "上海·普陀", district: "普陀", venue: "M50 陶艺工作室", distance: "4.3km",
      address: "上海市普陀区莫干山路 50 号 · 陶艺工作室（示例地址）",
      coord: { lng: 121.4438, lat: 31.2525 },
      price: "¥128（含材料）", hot: false, going: 22, capacity: 24, spotsLeft: 2,
      tags: ["艺术", "陶艺", "手作", "体验"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（工作室）", updated: "昨天",
      host: "M50 陶艺工作室（示例）", contact: "示例报名入口，非真实链接",
      desc: "从拉坯到上釉的完整体验，成品烧制后一周可取。老师全程指导，做出来的杯子真的能用。",
      transit: [
        { mode: "metro", line: "地铁 13 号线", detail: "江宁路站步行 11 分钟", time: "26 分钟", cost: "¥4", recommended: true },
        { mode: "bike", line: "共享单车", detail: "沿苏州河骑行", time: "16 分钟", cost: "¥1.5" },
      ],
      bring: ["围裙（可选）"], notes: "DEMO 数据，价格与时长均为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d21",
    },
    {
      id: "d22", demo: true, image: null, title: "云南菌子私厨 · 限 8 人小桌", category: "food",
      date: "周日 6.21", day: "sun", time: "12:00", end: "14:00",
      location: "上海·长宁", district: "长宁", venue: "巷子私厨（示例）", distance: "6.1km",
      address: "上海市长宁区愚园路弄内（示例地址）",
      coord: { lng: 121.4240, lat: 31.2180 },
      price: "¥168", hot: false, going: 7, capacity: 8, spotsLeft: 1,
      tags: ["美食", "私厨", "菌子", "小桌"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（私厨主理人）", updated: "1 小时前",
      host: "云南菌子私厨（示例）", contact: "示例报名入口，非真实链接",
      desc: "主理人从云南空运菌子做的时令菜，一桌只坐 8 人，边吃边聊。适合喜欢小众美食体验的同学。",
      transit: [
        { mode: "metro", line: "地铁 2/11 号线", detail: "江苏路站步行 10 分钟", time: "33 分钟", cost: "¥5", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 6 公里", time: "23 分钟", cost: "¥27" },
      ],
      bring: ["过敏史请提前告知"], notes: "DEMO 数据，菜单与价格为示例。", refund: "示例活动不支持退款。",
      registrationUrl: "https://example.com/gorgon-demo/d22",
    },
    {
      id: "d23", demo: true, image: null, title: "共青森林公园 · 晨间观鸟团", category: "outdoor",
      date: "周日 6.21", day: "sun", time: "07:00", end: "09:30",
      location: "上海·杨浦", district: "杨浦", venue: "共青森林公园南门", distance: "3.5km",
      address: "上海市杨浦区军工路 2000 号 · 共青森林公园南门（示例地址）",
      coord: { lng: 121.5460, lat: 31.3180 },
      price: "门票 ¥15", hot: false, going: 18, capacity: 30, spotsLeft: 12,
      tags: ["户外", "观鸟", "新手友好", "早起"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（自然观察小组）", updated: "昨天",
      host: "周末自然观察小组（示例）", contact: "示例报名入口，非真实链接",
      desc: "清晨在共青森林公园认鸟，有领队讲解、可借望远镜。适合想早起亲近自然、又怕一个人无聊的同学。",
      transit: [
        { mode: "bus", line: "公交 8 路", detail: "共青森林公园站下车即到", time: "22 分钟", cost: "¥2", recommended: true },
        { mode: "bike", line: "共享单车", detail: "沿军工路骑行", time: "16 分钟", cost: "¥1.5" },
      ],
      bring: ["望远镜（可借）", "饮水", "防蚊"], notes: "DEMO 数据，活动与门票均为示例。", refund: "活动免费，公园门票自理（示例）。",
      registrationUrl: "https://example.com/gorgon-demo/d23",
    },
    {
      id: "d24", demo: true, image: null, title: "考研自习搭子 · 周末刷题局", category: "study",
      date: "周六 6.20", day: "sat", time: "09:00", end: "18:00",
      location: "上海·松江", district: "松江", venue: "松江大学城图书馆", distance: "22.0km",
      address: "上海市松江区文汇路 · 大学城图书馆（示例地址）",
      coord: { lng: 121.2200, lat: 31.0350 },
      price: "免费", hot: false, going: 34, capacity: 40, spotsLeft: 6,
      tags: ["学习", "自习", "考研", "搭子"],
      trust: "aggregated", source: "DEMO DATA · 示例来源（考研群）", updated: "3 小时前",
      host: "考研自习互助组（示例）", contact: "示例报名入口，非真实链接",
      desc: "约定时间一起进图书馆，番茄钟节奏刷题，中午一起吃食堂。主打一个互相监督、不摆烂。",
      transit: [
        { mode: "metro", line: "地铁 9 号线", detail: "松江大学城站步行 12 分钟", time: "86 分钟", cost: "¥8", recommended: true },
        { mode: "taxi", line: "打车", detail: "约 22 公里", time: "52 分钟", cost: "¥75" },
      ],
      bring: ["复习资料", "耳机（可选）"], notes: "DEMO 数据，集合安排为示例。", refund: "免费活动，无需退款。",
      registrationUrl: "https://example.com/gorgon-demo/d24",
    },
  ],
};
