// Gorgon generated data — DO NOT EDIT BY HAND.
// ⚠️ DEMO DATA — produced by `python pipeline/run.py --export-gorgon`.
// This file is a pipeline artifact; ui_kits/app/data.js stays untouched
// and serves as fallback when this file is missing or empty.
window.GORGON_GENERATED_DATA = [
  {
    "id": "a02",
    "demo": true,
    "image": null,
    "title": "大模型应用实战工作坊(零基础)",
    "category": "study",
    "date": "周日 9.20",
    "day": "sun",
    "time": "13:30",
    "end": "17:00",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "创智天地 7 号楼",
    "distance": "1.2km",
    "address": "上海市杨浦区淞沪路创智天地",
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "¥29",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "AI",
      "工作坊",
      "零基础"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (ai_community)",
    "updated": "今天",
    "host": "复旦 AI 研习社",
    "contact": "https://example.com/ai/a02/signup",
    "desc": "带笔记本电脑，3小时跑通一个 RAG 应用。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://example.com/ai/a02/signup",
    "sourceUrl": "https://example.com/ai/a02",
    "duplicateOf": null
  },
  {
    "id": "a03",
    "demo": true,
    "image": null,
    "title": "周末民谣现场:城市夜晚与吉他",
    "category": "music",
    "date": "周日 9.20",
    "day": "sun",
    "time": "20:00",
    "end": "22:00",
    "location": "上海·长宁",
    "district": "长宁",
    "venue": "育音堂",
    "distance": "11.9km",
    "address": null,
    "coord": {
      "lng": 121.425,
      "lat": 31.221
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "音乐",
      "民谣",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (ai_community)",
    "updated": "今天",
    "host": "育音堂",
    "contact": null,
    "desc": "三位独立音乐人轮番上场。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://example.com/ai/a03",
    "duplicateOf": null
  },
  {
    "id": "a04",
    "demo": true,
    "image": null,
    "title": "开源之夏 · 上海 Meetup",
    "category": "social",
    "date": "周一 9.21",
    "day": "mon",
    "time": "14:00",
    "end": "17:00",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "杨浦区图书馆",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "开源",
      "技术",
      "meetup",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (ai_community)",
    "updated": "今天",
    "host": "开源社",
    "contact": "https://example.com/ai/a04/signup",
    "desc": "开源项目维护者面对面，Lightning Talk 报名中。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://example.com/ai/a04/signup",
    "sourceUrl": "https://example.com/ai/a04",
    "duplicateOf": null
  },
  {
    "id": "a05",
    "demo": true,
    "image": null,
    "title": "生成式艺术展:机器的梦",
    "category": "art",
    "date": "周六 9.19",
    "day": "sat",
    "time": "10:00",
    "end": "18:00",
    "location": "上海·徐汇",
    "district": "徐汇",
    "venue": "西岸美术馆",
    "distance": "13.0km",
    "address": null,
    "coord": {
      "lng": 121.463,
      "lat": 31.19
    },
    "price": "¥45",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "展览",
      "AIGC"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (ai_community)",
    "updated": "今天",
    "host": "西岸美术馆",
    "contact": null,
    "desc": "20位艺术家的 AIGC 作品联合展出。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://example.com/ai/a05",
    "duplicateOf": null
  },
  {
    "id": "a08",
    "demo": true,
    "image": null,
    "title": "AI 产品开放日 · 生成式应用 Demo Night",
    "category": "ai",
    "date": "周日 9.20",
    "day": "sun",
    "time": "19:00",
    "end": "21:30",
    "location": "上海·徐汇",
    "district": "徐汇",
    "venue": "西岸智塔 AI 空间",
    "distance": "13.0km",
    "address": null,
    "coord": {
      "lng": 121.463,
      "lat": 31.19
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "AI",
      "Demo",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (ai_community)",
    "updated": "今天",
    "host": "上海 AI 开发者社区",
    "contact": "https://example.com/ai/a08/signup",
    "desc": "十多个学生与独立开发者上台路演。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://example.com/ai/a08/signup",
    "sourceUrl": "https://example.com/ai/a08",
    "duplicateOf": null
  },
  {
    "id": "a10",
    "demo": true,
    "image": null,
    "title": "咖啡烘焙品鉴入门",
    "category": "food",
    "date": "周一 9.21",
    "day": "mon",
    "time": "10:00",
    "end": "12:00",
    "location": "上海·徐汇",
    "district": "徐汇",
    "venue": "永康路咖啡实验室",
    "distance": "13.0km",
    "address": null,
    "coord": {
      "lng": 121.463,
      "lat": 31.19
    },
    "price": "¥88",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "咖啡",
      "品鉴"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (ai_community)",
    "updated": "今天",
    "host": "咖啡实验室",
    "contact": "https://example.com/ai/a10/signup",
    "desc": "从生豆到杯子的入门课。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://example.com/ai/a10/signup",
    "sourceUrl": "https://example.com/ai/a10",
    "duplicateOf": null
  },
  {
    "id": "b03",
    "demo": true,
    "image": null,
    "title": "JavaScript Workshop:从零写一个解释器",
    "category": "study",
    "date": "周六 9.26",
    "day": "sat",
    "time": "14:00",
    "end": "17:30",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "创智天地 7 号楼",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "¥19",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "JavaScript",
      "编程"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (campus_bbs)",
    "updated": "今天",
    "host": "前端之友",
    "contact": "https://bbs.example.com/t/9003/form",
    "desc": "用 500 行 JS 写一个迷你 Lisp 解释器。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://bbs.example.com/t/9003/form",
    "sourceUrl": "https://bbs.example.com/t/9003",
    "duplicateOf": null
  },
  {
    "id": "b05",
    "demo": true,
    "image": null,
    "title": "秋日滨江骑行:杨浦大桥往返",
    "category": "outdoor",
    "date": "周日 9.20",
    "day": "sun",
    "time": "08:00",
    "end": "11:30",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "杨浦滨江",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "骑行",
      "户外",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (campus_bbs)",
    "updated": "今天",
    "host": "杨浦骑行会",
    "contact": null,
    "desc": "20km 休闲骑，需要自备自行车。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://bbs.example.com/t/9005",
    "duplicateOf": null
  },
  {
    "id": "b06",
    "demo": true,
    "image": null,
    "title": "公益图书馆整理志愿活动",
    "category": "charity",
    "date": "周日 9.20",
    "day": "sun",
    "time": "09:30",
    "end": "12:30",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "杨浦图书馆少儿馆",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "公益",
      "志愿",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (campus_bbs)",
    "updated": "今天",
    "host": "杨浦志愿者协会",
    "contact": "https://bbs.example.com/t/9006/form",
    "desc": "周末给社区图书馆整理书架，4小时志愿时长。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://bbs.example.com/t/9006/form",
    "sourceUrl": "https://bbs.example.com/t/9006",
    "duplicateOf": null
  },
  {
    "id": "b07",
    "demo": true,
    "image": null,
    "title": "周末旧书市集",
    "category": "market",
    "date": "周日 9.20",
    "day": "sun",
    "time": "10:00",
    "end": "18:00",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "大学路",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "市集",
      "旧书",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (campus_bbs)",
    "updated": "今天",
    "host": "大学路集市办",
    "contact": null,
    "desc": "100+ 摊位，淘绝版书。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://bbs.example.com/t/9007",
    "duplicateOf": null
  },
  {
    "id": "b08",
    "demo": true,
    "image": null,
    "title": "Open MIC 开放麦:九月场",
    "category": "music",
    "date": "周日 9.20",
    "day": "sun",
    "time": "19:30",
    "end": "22:00",
    "location": "上海·长宁",
    "district": "长宁",
    "venue": "育音堂",
    "distance": "11.9km",
    "address": null,
    "coord": {
      "lng": 121.425,
      "lat": 31.221
    },
    "price": "¥35",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "演出",
      "社交"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (campus_bbs)",
    "updated": "今天",
    "host": "育音堂",
    "contact": null,
    "desc": "脱口秀、民谣、诗歌都可以上台。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://bbs.example.com/t/9008",
    "duplicateOf": null
  },
  {
    "id": "b09",
    "demo": true,
    "image": null,
    "title": "AI 讲座:多模态大模型的2026",
    "category": "talk",
    "date": "周一 9.21",
    "day": "mon",
    "time": "18:30",
    "end": "20:30",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "复旦大学邯郸校区",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "AI",
      "讲座",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (campus_bbs)",
    "updated": "今天",
    "host": "复旦计算机学院",
    "contact": null,
    "desc": "高校教授分享多模态前沿进展。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://bbs.example.com/t/9009",
    "duplicateOf": null
  },
  {
    "id": "c03",
    "demo": true,
    "image": null,
    "title": "西岸音乐节 · 落日专场",
    "category": "music",
    "date": "周日 9.20",
    "day": "sun",
    "time": "16:00",
    "end": "21:30",
    "location": "上海·徐汇",
    "district": "徐汇",
    "venue": "西岸大草坪",
    "distance": "13.0km",
    "address": null,
    "coord": {
      "lng": 121.463,
      "lat": 31.19
    },
    "price": "¥150",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "音乐节",
      "户外"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (city_portal)",
    "updated": "今天",
    "host": "西岸集团",
    "contact": "https://portal.example.com/ev/703/reg",
    "desc": "五组乐队，草地上看日落。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://portal.example.com/ev/703/reg",
    "sourceUrl": "https://portal.example.com/ev/703",
    "duplicateOf": null
  },
  {
    "id": "c04",
    "demo": true,
    "image": null,
    "title": "宠物友好市集:毛孩子嘉年华",
    "category": "market",
    "date": "周一 9.21",
    "day": "mon",
    "time": "11:00",
    "end": "19:00",
    "location": "上海·杨浦",
    "district": "杨浦",
    "venue": "大学路中央广场",
    "distance": "1.2km",
    "address": null,
    "coord": {
      "lng": 121.523,
      "lat": 31.301
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "市集",
      "宠物",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (city_portal)",
    "updated": "今天",
    "host": "大学路集市办",
    "contact": null,
    "desc": "领养专区+宠物用品摊位。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://portal.example.com/ev/704",
    "duplicateOf": null
  },
  {
    "id": "c05",
    "demo": true,
    "image": null,
    "title": "无人驾驶公开课:从传感器到决策",
    "category": "talk",
    "date": "周六 9.26",
    "day": "sat",
    "time": "14:00",
    "end": "16:00",
    "location": "上海·嘉定",
    "district": "嘉定",
    "venue": "嘉定汽车博物馆",
    "distance": "24.7km",
    "address": null,
    "coord": {
      "lng": 121.266,
      "lat": 31.376
    },
    "price": "免费",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "讲座",
      "自动驾驶",
      "免费"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (city_portal)",
    "updated": "今天",
    "host": "汽车博物馆",
    "contact": "https://portal.example.com/ev/705/reg",
    "desc": "车企工程师带你入门自动驾驶系统。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://portal.example.com/ev/705/reg",
    "sourceUrl": "https://portal.example.com/ev/705",
    "duplicateOf": null
  },
  {
    "id": "c06",
    "demo": true,
    "image": null,
    "title": "夜校体验课:胶片摄影入门",
    "category": "study",
    "date": "周日 9.20",
    "day": "sun",
    "time": "18:00",
    "end": "20:30",
    "location": "上海·普陀",
    "district": "普陀",
    "venue": "M50创意园",
    "distance": "12.1km",
    "address": null,
    "coord": {
      "lng": 121.397,
      "lat": 31.249
    },
    "price": "¥60",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "摄影",
      "课程"
    ],
    "trust": "pipeline",
    "trustScore": 80,
    "source": "DEMO DATA · pipeline (city_portal)",
    "updated": "今天",
    "host": "M50影像社",
    "contact": null,
    "desc": "自带胶片机，现场教学冲扫流程。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": null,
    "sourceUrl": "https://portal.example.com/ev/706",
    "duplicateOf": null
  },
  {
    "id": "c07",
    "demo": true,
    "image": null,
    "title": "城市漫游:武康路建筑 reading 团",
    "category": "outdoor",
    "date": "周一 9.21",
    "day": "mon",
    "time": "15:00",
    "end": "17:00",
    "location": "上海·徐汇",
    "district": "徐汇",
    "venue": "武康大楼门口",
    "distance": "13.0km",
    "address": null,
    "coord": {
      "lng": 121.463,
      "lat": 31.19
    },
    "price": "¥29.9",
    "hot": false,
    "going": 0,
    "capacity": null,
    "spotsLeft": null,
    "tags": [
      "城市漫步",
      "历史"
    ],
    "trust": "pipeline",
    "trustScore": 85,
    "source": "DEMO DATA · pipeline (city_portal)",
    "updated": "今天",
    "host": "城市考古",
    "contact": "https://portal.example.com/ev/707/reg",
    "desc": "2小时漫步，讲武康路历史建筑。零宽字符测试→←这里。",
    "transit": [],
    "bring": [],
    "notes": "PIPELINE DEMO 数据，由 Gorgon data pipeline 自动生成。",
    "refund": null,
    "registrationUrl": "https://portal.example.com/ev/707/reg",
    "sourceUrl": "https://portal.example.com/ev/707",
    "duplicateOf": null
  }
];
