// Gorgon V1 — data bridge.
//
// Replaces the script-tag load order of the legacy app
// (data.js -> generated-data.js -> generated-search-demo.js ->
//  data-adapter.js) with explicit ES module imports. The underlying files
// are UNCHANGED and still live in ui_kits/app/ — two of them are pipeline
// artifacts regenerated by `python pipeline/run.py`, so they are imported
// here, never copied.
//
// Adapter rule (same as ui_kits/app/data-adapter.js):
//   - GORGON_GENERATED_DATA exists and is a non-empty array
//       -> use pipeline output as the activity list.
//   - otherwise -> keep data.js DEMO DATA untouched (fallback).
// data.js is NEVER overwritten by anyone.

import "../../../ui_kits/app/data.js";
import "../../../ui_kits/app/generated-data.js";
import "../../../ui_kits/app/generated-search-demo.js";

const data = window.GORGON_DATA;
const gen = window.GORGON_GENERATED_DATA;

if (Array.isArray(gen) && gen.length > 0 && data && typeof data === "object") {
  data.activities = gen;
  data.generatedFromPipeline = true;
}

export const GORGON_DATA = data;
export const GORGON_SEARCH_DEMO = window.GORGON_SEARCH_DEMO || null;
